apiVersion: v1
kind: Service
metadata:
  name: auth-cluster-service
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - name: auth
      protocol: TCP
      port: 80
      targetPort: 80
