apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
