apiVersion: v1
kind: Service
metadata:
  name: tasks-loadbalancer-service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - name: tasks-loadbalancer-service
      protocol: TCP
      port: 8080
      targetPort: 8000
