apiVersion: v1
kind: Service
metadata:
  name: users-loadbalancer-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - name: users
      protocol: TCP
      port: 80
      targetPort: 8080
